services:
  crypto-front:
    build: ./frontend

    #DEV
    volumes:
      - ./frontend:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #VED
  crypto-back:
    build: ./backend

    #DEV
    volumes:
      - ./backend:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #VED

